---
title: "Compute Vitiligo PRS in VIGOR Cohort"
author: "Gen Roberts"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here, lib.loc="/home/genevieve.roberts-umw/R/x86_64-conda-linux-gnu-library/4.2")
library(tidyverse, lib.loc = "/share/pkg/conda/r/4.2.2/lib/R/library")
library(data.table)


#install.packages('rsnps', repos = c('https://ropensci.r-universe.dev', 'https://cloud.r-project.org'))
library(rsnps)

#install.packages('LDlinkR')
library(LDlinkR)
```


```{r}
weights_path <- str_c(here(), "/Vitiligo_Risk_Score_Weights_Roberts2019.csv")
weights <- fread(weights_path)
snps <- weights$SNP

bim_path <- "/pi/manuel.garber-umw/human/VIGOR/tj/ibd/all_samples_qc.bim"
bim <- fread(bim_path) %>%
  mutate(chr_pos=str_c(V1, ":", V4))
```

```{r}
#get a list of the rsIDs not in the bim
bim_missing_snps <- setdiff(snps, bim$V2)
missing_snp_query <- ncbi_snp_query(bim_missing_snps) %>%
  mutate(chr_pos=str_c(chromosome, ":", bp))
missing_snp_query
```

```{r}
#left join with the bim file to see if we can rescue any of these
rescue_snps <- left_join(missing_snp_query, bim, on="chr_pos") %>%
  filter(!is.na(V1))
rescue_snps
```


```{r}
get_best_proxy_snps <- function(query_snps, token = "342bb55e0297", bim) {
  # Ensure query_snp is a list if it's not
  if (length(query_snps) == 1) {
    query_snps <- list(query_snps)
  }
  
  # Create an empty list to store the best proxy results for each query SNP
  best_proxies <- list()
  
  # Loop through each query SNP
  for (query_snp in query_snps) {
    # Get proxy SNPs using LDproxy function
    proxy_snps <- LDproxy(query_snp, token = token)
    
    # Find the best proxy SNP
    best_proxy <- proxy_snps %>%
      mutate(SNP = query_snp) %>%
      mutate(in_bim = RS_Number %in% bim$V2) %>%
      filter(in_bim == TRUE) %>%
      arrange(desc(R2), desc(Dprime)) %>%
      slice(1) %>%
      select(SNP, proxy_SNP = RS_Number, Alleles, Correlated_Alleles, R2, Dprime, MAF) %>%
      tibble()
    
    # Add the best proxy to the list
    best_proxies[[query_snp]] <- best_proxy
  }
  
  # Combine all results into a single dataframe
  best_proxies_df <- bind_rows(best_proxies)
  
  return(best_proxies_df)
}

best_proxies <- get_best_proxy_snps(query_snps=bim_missing_snps,
                                   token ="342bb55e0297",
                                   bim=bim)
best_proxies
```



```{r}
updated_table <- weights %>%
  left_join(best_proxies, by = c("SNP")) %>%
  mutate(
    effect_allele = EA_RiskAlleles,
    tag_snp_effect_allele = case_when(
      effect_allele == "A" ~ str_extract(Correlated_Alleles, "(?<=A=)[A-Za-z]+"),
      effect_allele == "T" ~ str_extract(Correlated_Alleles, "(?<=T=)[A-Za-z]+"),
      effect_allele == "G" ~ str_extract(Correlated_Alleles, "(?<=G=)[A-Za-z]+"),
      effect_allele == "C" ~ str_extract(Correlated_Alleles, "(?<=C=)[A-Za-z]+"),
      effect_allele == "D" ~ str_extract(Correlated_Alleles, "(?<=-=)[A-Za-z]+"),
      effect_allele == "I" ~ str_extract(Correlated_Alleles, "(?<=([A-Za-z])=)[A-Za-z]+"),
      TRUE ~ NA_character_
    ),
    other_proxy_allele = case_when(
      tag_snp_effect_allele %in% c("I", "D") ~ ifelse(
        tag_snp_effect_allele == "I", "D", "I"
      ),
      !is.na(effect_allele) & !is.na(Alleles) ~ 
        Alleles %>%
        str_remove_all("\\(|\\)|/") %>% # Remove parentheses and slash
        str_remove(tag_snp_effect_allele), # Remove the effect allele
      TRUE ~ NA_character_
    ),
    # Create proxy_snp summary column with annotations
    proxy_snp_summary = if_else(!is.na(proxy_SNP), paste(
      "Index_SNP:", SNP,
      "Proxy_SNP:", proxy_SNP,
      "R2:", R2,
      "Dprime:", Dprime,
      "MAF:", MAF,
      "Correlated_Alleles:", Correlated_Alleles
    ), NA_character_)
  ) %>%
  # Conditionally update SNP only if proxy_SNP is not NA
  mutate(SNP = if_else(!is.na(proxy_SNP), proxy_SNP, SNP)) %>%
  mutate(RA_OA = if_else(!is.na(proxy_SNP), str_c(tag_snp_effect_allele, "/", other_proxy_allele), RA_OA)) %>%
  mutate(EA_RiskAlleles = if_else(!is.na(proxy_SNP), tag_snp_effect_allele, EA_RiskAlleles))%>%
  # Select desired columns and drop redundant ones
  select(-proxy_SNP, -R2, -Dprime, -MAF, -Correlated_Alleles, -tag_snp_effect_allele, -other_proxy_allele, -Alleles)

updated_table
```

```{r}
process_proxy_data <- function(weights, best_proxies, effect_allele_col) {
  
  updated_table <- weights %>%
    left_join(best_proxies, by = c("SNP")) %>%
    mutate(
      effect_allele = !!sym(effect_allele_col),
      tag_snp_effect_allele = case_when(
        effect_allele == "A" ~ str_extract(Correlated_Alleles, "(?<=A=)[A-Za-z]+"),
        effect_allele == "T" ~ str_extract(Correlated_Alleles, "(?<=T=)[A-Za-z]+"),
        effect_allele == "G" ~ str_extract(Correlated_Alleles, "(?<=G=)[A-Za-z]+"),
        effect_allele == "C" ~ str_extract(Correlated_Alleles, "(?<=C=)[A-Za-z]+"),
        effect_allele == "D" ~ str_extract(Correlated_Alleles, "(?<=-=)[A-Za-z]+"),
        effect_allele == "I" ~ str_extract(Correlated_Alleles, "(?<=([A-Za-z])=)[A-Za-z]+"),
        TRUE ~ NA_character_
      ),
      other_proxy_allele = case_when(
        tag_snp_effect_allele %in% c("I", "D") ~ ifelse(
          tag_snp_effect_allele == "I", "D", "I"
        ),
        !is.na(effect_allele) & !is.na(Alleles) ~ 
          Alleles %>%
          str_remove_all("\\(|\\)|/") %>% # Remove parentheses and slash
          str_remove(tag_snp_effect_allele), # Remove the effect allele
        TRUE ~ NA_character_
      ),
      # Create proxy_snp summary column with annotations
      proxy_snp_summary = if_else(!is.na(proxy_SNP), paste(
        "Index_SNP:", SNP,
        "Proxy_SNP:", proxy_SNP,
        "R2:", R2,
        "Dprime:", Dprime,
        "MAF:", MAF,
        "Correlated_Alleles:", Correlated_Alleles
      ), NA_character_),
    ) %>%
    # Conditionally update SNP only if proxy_SNP is not NA
    mutate(SNP = if_else(!is.na(proxy_SNP), proxy_SNP, SNP)) %>%
    mutate(RA_OA = if_else(!is.na(proxy_SNP), str_c(tag_snp_effect_allele, "/", other_proxy_allele), RA_OA)) %>%
    mutate(!!effect_allele_col := if_else(!is.na(proxy_SNP), tag_snp_effect_allele, !!sym(effect_allele_col))) %>%
    # Select desired columns and drop redundant ones
    select(-proxy_SNP, -R2, -Dprime, -MAF,
           -Correlated_Alleles,
           -tag_snp_effect_allele, -other_proxy_allele, -Alleles)

  return(updated_table)
}

updated_table <- process_proxy_data(
  weights, 
  best_proxies, 
  "EA_RiskAlleles"
)
updated_table
```

